### ISSUE TITLE
.sh extension removed after download

### ISSUE THREAD

**Issue by Lyton505** [kontr0x/github-desktop-install#2]
Running:

`curl -fsSL https://raw.githubusercontent.com/kontr0x/github-desktop-install/main/installGitHubDesktop.sh -o installGitHubDesktop`

removes the .sh extension because of `-o installGitHubDesktop` without the .sh after _installGitHubDesktop_. As such, running `bash ./installGitHubDesktop` fails to execute. 

minor issue

**Comment by Lyton505** [comment]
Never mind. I was the one who made an error

**Comment by kontr0x** [comment]
No worries, I'm glad people want to contribute.
