### ISSUE TITLE
script failing: does not exist, check your permissions!

### ISSUE THREAD

**Issue by mratanusarkar** [kontr0x/github-desktop-install#3]
I am trying to use the script to install github desktop in my Linux machine (Ubuntu 20.04.6 LTS)

I have tried `curl`, `wget` and even manually downloading `installGitHubDesktop.sh` and running the sh script (both in sudo and in user mode), but I keep getting the following error:

```bash
Starting install script...

curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Downloading  ...
Warning: Remote filename has no length!                                                                                                                                                                   
curl: (23) Failed writing body (0 != 1361)

Download complete!
 does not exist, check your permissions!
```

I tried to give the file executable permissions but whatever I do, it keeps failing with the above error.
please help me if I am missing out on something.

**Comment by kontr0x** [comment]
Hello @mratanusarkar, what is the error you are facing when downloading the script via curl/wget?

What shell are you using and how do you start the script after you downloaded it manually? Did you use the commands supplied in the README of the repo?

Another question, are you behind an aggressiv firewall or are you aware that some of your internet access is restricted?

**Comment by kontr0x** [comment]
Hello again @mratanusarkar, sorry I had no time to test the script. 

It looks like, the target repository from GitHub desktop changed their release naming.
I'm already working on the issue, after it is fixed this issue will be closed.

You most likely do nothing wrong, so I am sorry for the inconvenience.

Have a nice day.

**Comment by kontr0x** [comment]
Script is updated and should work as normal.

**Comment by mratanusarkar** [comment]
> It looks like, the target repository from GitHub desktop changed their release naming.

Hey @kontr0x thanks for getting back so quick and resolving the issue!
It's cool that the script is functional again for all the Linux users 😇
