### ISSUE TITLE
remove the installation file after successful install

### ISSUE THREAD

**Issue by mratanusarkar** [kontr0x/github-desktop-install#4]
It's irritating that after successful installation, the script doesn't auto remove the downloaded artifacts.

example, for my case, the script downloaded `GitHubDesktop-linux-amd64-3.3.3-linux2.deb`, which I had to manually remove with `rm GitHubDesktop-linux-amd64-3.3.3-linux2.deb`. 

It would be good to add a cleanup line at the end of script, and it would be a good practice as well as help in saving disk space.

**Comment by kontr0x** [comment]
Hello @mratanusarkar, your feature got implemented in the latest [commit](https://github.com/kontr0x/github-desktop-install/commit/d88f2f5842806d8c4862078c57fed6d312f95ec3). Thank you for the idea!

**Comment by mratanusarkar** [comment]
@kontr0x you're welcome!
PS: Just used the latest version of the script and it works like a charm!
